"""
Napisz algorytm,
ktory w podanym lancuchu DNA odajdz k-elementowy najczesciej powtarzajacy sie fragment.
Gdy najczesciej wystepujacych fragmentow jest wiecej niz 1, wypisz ich cala list oddzielona spacjami

Przeprocesuj plik DNA_losowe.txt i odnajdz fragmenty dla
k rownych 3, 4, 5, 6, 7 i 8
Wartosci zapisz do pliku DNA_analiza.txt

Za zestawy testowe do sprawdzenia algorytmu przyjmij:

# string = "TGGTAGCGACGTTGGTCCCGCCGCTTGAGAATCTGGATGAACATAAGCTCCCACTTGGCTTATTCAGAGAACTGGTCAACACTTGTCTCTCCCAGCCAGGTCTGACCACCGGGCAACTTTTAGAGCACTATCGTGGTACAAATAATGCTGCCAC"
# k = 3
# answer = "TGG"

# string = "CAGTGGCAGATGACATTTTGCTGGTCGACTGGTTACAACAACGCCTGGGGCTTTTGAGCAACGAGACTTTTCAATGTTGCACCGTTTGCTGCATGATATTGAAAACAATATCACCAAATAAATAACGCCTTAGTAAGTAGCTTTT"
# k = 4
# answer = "TTTT"

# string = "ATACAATTACAGTCTGGAACCGGATGAACTGGCCGCAGGTTAACAACAGAGTTGCCAGGCACTGCCGCTGACCAGCAACAACAACAATGACTTTGACGCGAAGGGGATGGCATGAGCGAACTGATCGTCAGCCGTCAGCAACGAGTATTGTTGCTGACCCTTAACAATCCCGCCGCACGTAATGCGCTAACTAATGCCCTGCTG"
# k = 5
# answer = "AACAA"

# string = "CCAGCGGGGGTTGATGCTCTGGGGGTCACAAGATTGCATTTTTATGGGGTTGCAAAAATGTTTTTTACGGCAGATTCATTTAAAATGCCCACTGGCTGGAGACATAGCCCGGATGCGCGTCTTTTACAACGTATTGCGGGGTAAAATCGTAGATGTTTTAAAATAGGCGTAAC"
# k = 5
# answer = "AAAAT GGGGT TTTTA"
"""